In [3]:
import torch
import math

In [10]:
x = torch.empty(2,3)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-3.3437e+14,  4.4481e-41,  2.0413e-20],
        [ 0.0000e+00,  4.4842e-44,  0.0000e+00]])


In [14]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


In [19]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


In [20]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[2.0455e-20, 0.0000e+00, 2.0400e-20],
         [0.0000e+00, 4.2160e-01, 6.9054e-02]],

        [[1.0842e-19, 0.0000e+00, 2.0374e-20],
         [0.0000e+00, 2.1386e-23, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[2.0400e-20, 0.0000e+00, 1.0227e-20],
         [0.0000e+00, 1.1210e-43, 0.0000e+00]],

        [[8.9683e-44, 0.0000e+00, 2.0493e-20],
         [0.0000e+00, 0.0000e+00, 1.5046e-36]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


In [21]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


In [28]:
a = torch.ones((2, 2), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1],
        [1, 1]], dtype=torch.int16)
tensor([[18.3283,  0.2118, 18.4972],
        [ 9.8370,  3.8937, 16.1945]], dtype=torch.float64)
tensor([[18,  0, 18],
        [ 9,  3, 16]], dtype=torch.int32)


In [29]:
ones = torch.zeros(2, 3) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


In [30]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])


RuntimeError: The size of tensor a (3) must match the size of tensor b (2) at non-singleton dimension 1

In [33]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1,4) * 2)

print(rand)
print(doubled)

tensor([[0.8328, 0.8444, 0.2941, 0.3788],
        [0.4567, 0.0649, 0.6677, 0.7826]])
tensor([[1.6657, 1.6888, 0.5882, 0.7576],
        [0.9134, 0.1298, 1.3355, 1.5652]])



The rules for broadcasting are:

-   Each tensor must have at least one dimension - no empty tensors.
-   Comparing the dimension sizes of the two tensors, *going from last
    to first:*
    -   Each dimension must be equal, *or*
    -   One of the dimensions must be of size 1, *or*
    -   The dimension does not exist in one of the tensors



In [34]:
a =     torch.ones(4, 3, 2)

b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.1332, 0.0023],
         [0.4945, 0.3857],
         [0.9883, 0.4762]],

        [[0.1332, 0.0023],
         [0.4945, 0.3857],
         [0.9883, 0.4762]],

        [[0.1332, 0.0023],
         [0.4945, 0.3857],
         [0.9883, 0.4762]],

        [[0.1332, 0.0023],
         [0.4945, 0.3857],
         [0.9883, 0.4762]]])
tensor([[[0.7242, 0.7242],
         [0.0776, 0.0776],
         [0.4004, 0.4004]],

        [[0.7242, 0.7242],
         [0.0776, 0.0776],
         [0.4004, 0.4004]],

        [[0.7242, 0.7242],
         [0.0776, 0.0776],
         [0.4004, 0.4004]],

        [[0.7242, 0.7242],
         [0.0776, 0.0776],
         [0.4004, 0.4004]]])
tensor([[[0.9877, 0.0352],
         [0.9877, 0.0352],
         [0.9877, 0.0352]],

        [[0.9877, 0.0352],
         [0.9877, 0.0352],
         [0.9877, 0.0352]],

        [[0.9877, 0.0352],
         [0.9877, 0.0352],
         [0.9877, 0.0352]],

        [[0.9877, 0.0352],
         [0.9877, 0.0352],
         [0.9877, 0.0352]]])


In [37]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print(a)
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition

tensor([[ 0.0921,  0.0792, -0.3893, -0.6054],
        [-0.3429,  0.1310, -0.9869,  0.5530]])
Common functions:
tensor([[0.0921, 0.0792, 0.3893, 0.6054],
        [0.3429, 0.1310, 0.9869, 0.5530]])
tensor([[1., 1., -0., -0.],
        [-0., 1., -0., 1.]])
tensor([[ 0.,  0., -1., -1.],
        [-1.,  0., -1.,  0.]])
tensor([[ 0.0921,  0.0792, -0.3893, -0.5000],
        [-0.3429,  0.1310, -0.5000,  0.5000]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.3534, 0.7016],
        [0.6826, 0.9413]])
tensor([[1.0602, 2.1048],
        [2.0479, 2.8240]])
torch.return_types.linalg_svd(
U=tensor([[-0.5579, -0.8299],
        [-0.8299,  0.5

In [38]:
# Altering Tensors in Place
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


In [39]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.4460, 0.9289],
        [0.6293, 0.6264]])

After adding:
tensor([[1.4460, 1.9289],
        [1.6293, 1.6264]])
tensor([[1.4460, 1.9289],
        [1.6293, 1.6264]])
tensor([[0.4460, 0.9289],
        [0.6293, 0.6264]])

After multiplying
tensor([[0.1989, 0.8628],
        [0.3960, 0.3924]])
tensor([[0.1989, 0.8628],
        [0.3960, 0.3924]])


Note that these in-place arithmetic functions are methods on the
`torch.Tensor` object, not attached to the `torch` module like many
other functions (e.g., `torch.sin()`). As you can see from `a.add_(b)`,
*the calling tensor is the one that gets changed in place.*

There is another option for placing the result of a computation in an
existing, allocated tensor. Many of the methods and functions we've seen
so far - including creation methods! - have an `out` argument that lets
you specify a tensor to receive the output. If the `out` tensor is the
correct shape and `dtype`, this can happen without a new memory
allocation:


In [ ]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

In [ ]:
# Copying Tensors

a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

In [ ]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

**There is an important thing to be aware of when using
\`\`clone()\`\`.** If your source tensor has autograd, enabled then so
will the clone. **This will be covered more deeply in the video on
autograd,** but if you want the light version of the details, continue
on.

*In many cases, this will be what you want.* For example, if your model
has multiple computation paths in its `forward()` method, and *both* the
original tensor and its clone contribute to the model's output, then to
enable model learning you want autograd turned on for both tensors. If
your source tensor has autograd enabled (which it generally will if it's
a set of learning weights or derived from a computation involving the
weights), then you'll get the result you want.

On the other hand, if you're doing a computation where *neither* the
original tensor nor its clone need to track gradients, then as long as
the source tensor has autograd turned off, you're good to go.

*There is a third case,* though: Imagine you're performing a computation
in your model's `forward()` function, where gradients are turned on for
everything by default, but you want to pull out some values mid-stream
to generate some metrics. In this case, you *don't* want the cloned copy
of your source tensor to track gradients - performance is improved with
autograd's history tracking turned off. For this, you can use the
`.detach()` method on the source tensor:


In [ ]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

 ### Accelerator

In [2]:
import torch
if torch.accelerator.is_available():
    print('We have an accelerator!')
else:
    print('Sorry, CPU only.')

We have an accelerator!


In [3]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

tensor([[0.2286, 0.8488],
        [0.1916, 0.3454]], device='cuda:0')


By default, new tensors are created on the CPU, so we have to specify
when we want to create our tensor on the accelerator with the optional
`device` argument. You can see when we print the new tensor, PyTorch
informs us which device it's on (if it's not on CPU).

You can query the number of accelerators with
`torch.accelerator.device_count()`. If you have more than one
accelerator, you can specify them by index, take CUDA for example:
`device='cuda:0'`, `device='cuda:1'`, etc.

As a coding practice, specifying our devices everywhere with string
constants is pretty fragile. In an ideal world, your code would perform
robustly whether you're on CPU or accelerator hardware. You can do this
by creating a device handle that can be passed to your tensors instead
of a string:


In [4]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cuda
tensor([[0.9551, 0.3549],
        [0.1472, 0.5082]], device='cuda:0')


If you have an existing tensor living on one device, you can move it to
another with the `to()` method. The following line of code creates a
tensor on CPU, and moves it to whichever device handle you acquired in
the previous cell.


In [5]:
y = torch.rand(2, 2)
y = y.to(my_device)

It is important to know that in order to do computation involving two or
more tensors, *all of the tensors must be on the same device*. The
following code will throw a runtime error, regardless of whether you
have an accelerator device available, take CUDA for example:

``` {.python}
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cuda')
z = x + y  # exception will be thrown
```


Manipulating Tensor Shapes
==========================

Sometimes, you'll need to change the shape of your tensor. Below, we'll
look at a few common cases, and how to handle them.

Changing the Number of Dimensions
---------------------------------

One case where you might need to change the number of dimensions is
passing a single instance of input to your model. PyTorch models
generally expect *batches* of input.

For example, imagine having a model that works on 3 x 226 x 226 images
-a 226-pixel square with 3 color channels. When you load and transform
it, you'll get a tensor of shape `(3, 226, 226)`. Your model, though, is
expecting input of shape `(N, 3, 226, 226)`, where `N` is the number of
images in the batch. So how do you make a batch of one?


In [6]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)

print(a.shape)
print(b.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


The `unsqueeze()` method adds a dimension of extent 1. `unsqueeze(0)`
adds it as a new zeroth dimension - now you have a batch of one!

So if that's *un*squeezing? What do we mean by squeezing? We're taking
advantage of the fact that any dimension of extent 1 *does not* change
the number of elements in the tensor.


In [7]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.0242]]]]])


Continuing the example above, let's say the model's output is a
20-element vector for each input. You would then expect the output to
have shape `(N, 20)`, where `N` is the number of instances in the input
batch. That means that for our single-input batch, we'll get an output
of shape `(1, 20)`.

What if you want to do some *non-batched* computation with that output
-something that's just expecting a 20-element vector?


In [8]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.3427, 0.3659, 0.0456, 0.3792, 0.3274, 0.4905, 0.4994, 0.9025, 0.6398,
         0.7835, 0.0425, 0.8359, 0.7713, 0.8940, 0.0248, 0.2115, 0.0263, 0.3915,
         0.6138, 0.2750]])
torch.Size([20])
tensor([0.3427, 0.3659, 0.0456, 0.3792, 0.3274, 0.4905, 0.4994, 0.9025, 0.6398,
        0.7835, 0.0425, 0.8359, 0.7713, 0.8940, 0.0248, 0.2115, 0.0263, 0.3915,
        0.6138, 0.2750])
torch.Size([2, 2])
torch.Size([2, 2])


You can see from the shapes that our 2-dimensional tensor is now
1-dimensional, and if you look closely at the output of the cell above
you'll see that printing `a` shows an "extra" set of square brackets
`[]` due to having an extra dimension.

You may only `squeeze()` dimensions of extent 1. See above where we try
to squeeze a dimension of size 2 in `c`, and get back the same shape we
started with. Calls to `squeeze()` and `unsqueeze()` can only act on
dimensions of extent 1 because to do otherwise would change the number
of elements in the tensor.

Another place you might use `unsqueeze()` is to ease broadcasting.
Recall the example above where we had the following code:

``` {.python}
a = torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)
```

The net effect of that was to broadcast the operation over dimensions 0
and 2, causing the random, 3 x 1 tensor to be multiplied element-wise by
every 3-element column in `a`.

What if the random vector had just been 3-element vector? We'd lose the
ability to do the broadcast, because the final dimensions would not
match up according to the broadcasting rules. `unsqueeze()` comes to the
rescue:


In [ ]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

The `squeeze()` and `unsqueeze()` methods also have in-place versions,
`squeeze_()` and `unsqueeze_()`:


In [ ]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

Sometimes you'll want to change the shape of a tensor more radically,
while still preserving the number of elements and their contents. One
case where this happens is at the interface between a convolutional
layer of a model and a linear layer of the model - this is common in
image classification models. A convolution kernel will yield an output
tensor of shape *features x width x height,* but the following linear
layer expects a 1-dimensional input. `reshape()` will do this for you,
provided that the dimensions you request yield the same number of
elements as the input tensor has:


In [ ]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The <code>(6 * 20 * 20,)</code> argument in the final line of the cellabove is because PyTorch expects a  when specifying atensor shape - but when the shape is the first argument of a method, itlets us cheat and just use a series of integers. Here, we had to add theparentheses and comma to convince the method that this is really aone-element tuple.</p>

</div>

When it can, `reshape()` will return a *view* on the tensor to be
changed - that is, a separate tensor object looking at the same
underlying region of memory. *This is important:* That means any change
made to the source tensor will be reflected in the view on that tensor,
unless you `clone()` it.

There *are* conditions, beyond the scope of this introduction, where
`reshape()` has to return a tensor carrying a copy of the data. For more
information, see the
[docs](https://pytorch.org/docs/stable/torch.html#torch.reshape).


NumPy Bridge
============

In the section above on broadcasting, it was mentioned that PyTorch's
broadcast semantics are compatible with NumPy's - but the kinship
between PyTorch and NumPy goes even deeper than that.

If you have existing ML or scientific code with data stored in NumPy
ndarrays, you may wish to express that same data as PyTorch tensors,
whether to take advantage of PyTorch's GPU acceleration, or its
efficient abstractions for building ML models. It's easy to switch
between ndarrays and PyTorch tensors:


In [10]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape and containing the same data
as the NumPy array, going so far as to keep NumPy's default 64-bit float
data type.

The conversion can just as easily go the other way:


In [11]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.1986, 0.5502, 0.7027],
        [0.6815, 0.0026, 0.1722]])
[[0.19857597 0.5502041  0.70271724]
 [0.6814561  0.00256592 0.17224008]]


It is important to know that these converted objects are using *the same
underlying memory* as their source objects, meaning that changes to one
are reflected in the other:


In [12]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.19857597  0.5502041   0.70271724]
 [ 0.6814561  17.          0.17224008]]
